# ==================================================================================================================== #
# Authors:                                                                                                             #
#   Patrick Lehmann                                                                                                    #
#                                                                                                                      #
# License:                                                                                                             #
# ==================================================================================================================== #
# Copyright 2024-2026 Electronic Design Automation Abstraction (EDA²)                                                  #
#                                                                                                                      #
# Licensed under the Apache License, Version 2.0 (the "License");                                                      #
# you may not use this file except in compliance with the License.                                                     #
# You may obtain a copy of the License at                                                                              #
#                                                                                                                      #
#   http://www.apache.org/licenses/LICENSE-2.0                                                                         #
#                                                                                                                      #
# Unless required by applicable law or agreed to in writing, software                                                  #
# distributed under the License is distributed on an "AS IS" BASIS,                                                    #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                                             #
# See the License for the specific language governing permissions and                                                  #
# limitations under the License.                                                                                       #
#                                                                                                                      #
# SPDX-License-Identifier: Apache-2.0                                                                                  #
# ==================================================================================================================== #
name: Example C++

on:
  workflow_call:

jobs:
  Cpp-GoogleTest:
    runs-on: ubuntu-26.04
    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v7

      - name: 🔧 Install dependencies
        run: sudo apt-get install -y --no-install-recommends ninja-build

      - name: 🛠 Run CMake
        run: |
          cd examples/Cpp/GoogleTest
          cmake -B build -G Ninja
          cmake --build build

      - name: ✅ Run unit tests (directly)
        run: |
          cd examples/Cpp/GoogleTest
          ./build/unit_tests --gtest_output=xml:gtest.xml

      - name: ✅ Run unit tests (by ctest)
        run: |
          cd examples/Cpp/GoogleTest
          ctest --test-dir build/ --output-junit ../ctest.xml

      - name: List generated XML reports
        run: |
          ls -lAh examples/Cpp/GoogleTest/*.xml

      - name: 📤 Upload JUnit XML files as artifact
        uses: pyTooling/upload-artifact@v7
        with:
          name: Cpp-GoogleTest
          path: examples/Cpp/GoogleTest/*.xml
